version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dataops
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: dataops
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
